#!/bin/bash

# 🚀 GitHub Repository Setup Script
# Run this script after creating your GitHub repository

echo "🎯 Real Estate CRM - GitHub Setup"
echo "=================================="
echo ""
echo "📝 Steps to connect to GitHub:"
echo ""
echo "1️⃣  First, create a new repository on GitHub:"
echo "   - Go to https://github.com/new"
echo "   - Repository name: real-estate-crm (or your preferred name)"
echo "   - Description: Real Estate CRM with Supabase integration"
echo "   - Make it Public or Private (your choice)"
echo "   - DON'T initialize with README, .gitignore, or license (we already have them)"
echo ""
echo "2️⃣  Then run these commands:"
echo ""
echo "   # Add your GitHub repository as remote origin"
echo "   git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO_NAME.git"
echo ""
echo "   # Push to GitHub"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3️⃣  Example with actual values:"
echo "   git remote add origin https://github.com/johndoe/real-estate-crm.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "🎉 After pushing, your repository will be live on GitHub!"
echo ""
echo "📋 Current git status:"
git status --short
echo ""
echo "📊 Project stats:"
echo "   Files: $(find . -type f | wc -l | tr -d ' ')"
echo "   Directories: $(find . -type d | wc -l | tr -d ' ')"
echo "   Lines of code: $(find . -name "*.js" -o -name "*.jsx" -o -name "*.sql" | xargs wc -l | tail -1 | awk '{print $1}')"
echo ""
echo "🔗 Useful links after GitHub setup:"
echo "   - Clone: git clone https://github.com/YOUR_USERNAME/YOUR_REPO_NAME.git"
echo "   - Issues: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME/issues"
echo "   - Actions: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME/actions"
echo ""
echo "✅ Your CRS project is ready for GitHub! 🚀"
